name: Build Hasura Supergraph Manifest

on:
  push:
    branches:
      - main  # Change to your default branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install ddn CLI
      run: |
        curl -L https://graphql-engine-cdn.hasura.io/ddn/cli/v1/get.sh | bash

    - name: Login to ddn
      run: ddn login --pat ${{ secrets.HASURA_PAT }}

    - name: Build supergraph manifest
      run: ddn build supergraph-manifest
